package com.predictiveshard.optimization;

import java.util.*;

/** Deterministic capacity-constrained heuristic. Percentages always sum to 100. */
public final class TrafficOptimizer {
  public record Shard(String id,double allocation,double utilization,double risk,double latencyMs,double maximumAllocation) {}
  public record Allocation(String shardId,double currentTrafficPercent,double recommendedTrafficPercent,double deltaPercent,double expectedLatency,double expectedRisk) {}
  public record Result(List<Allocation> allocations,double objectiveScoreBefore,double objectiveScoreAfter,double estimatedRiskReduction,double estimatedMigrationCost,boolean feasible,String reason) {}
  public Result optimize(String sourceId,List<Shard> input,double targetRisk,double maxMove){var shards=new ArrayList<>(input);var source=shards.stream().filter(s->s.id().equals(sourceId)).findFirst().orElseThrow();if(maxMove<=0||maxMove>25)throw new IllegalArgumentException("maxMove must be within (0,25]");var next=new HashMap<String,Double>();shards.forEach(s->next.put(s.id(),s.allocation()));double remaining=Math.min(maxMove,Math.max(0,source.allocation()));var candidates=shards.stream().filter(s->!s.id().equals(sourceId)&&s.risk()<.7&&s.utilization()<.8&&s.maximumAllocation()>s.allocation()).sorted(Comparator.comparingDouble((Shard s)->-(s.maximumAllocation()-s.allocation())+s.risk()*20+s.latencyMs()/1000)).toList();for(var c:candidates){double movable=Math.min(remaining,Math.max(0,c.maximumAllocation()-next.get(c.id())));if(movable<=0)continue;next.merge(sourceId,-movable,Double::sum);next.merge(c.id(),movable,Double::sum);remaining-=movable;if(remaining<.001)break;}double moved=source.allocation()-next.get(sourceId);if(moved<.001)return new Result(List.of(),objective(input),objective(input),0,0,false,"NO_FEASIBLE_REMEDIATION");var allocations=shards.stream().map(s->{double n=next.get(s.id());double projected=s.id().equals(sourceId)?Math.max(0,s.risk()*(1-moved/Math.max(1,s.allocation()))):Math.min(1,s.risk()+Math.max(0,n-s.allocation())/100*.35);return new Allocation(s.id(),s.allocation(),n,n-s.allocation(),s.latencyMs(),projected);}).toList();double after=allocations.stream().mapToDouble(a->a.expectedRisk()*a.recommendedTrafficPercent()/100).sum();return new Result(allocations,objective(input),after,Math.max(0,source.risk()-allocations.stream().filter(a->a.shardId().equals(sourceId)).findFirst().orElseThrow().expectedRisk()),moved,true,"SAFE_REDISTRIBUTION");}
  private double objective(List<Shard> ss){return ss.stream().mapToDouble(s->s.risk()*s.allocation()/100+s.latencyMs()/10000).sum();}
}
