import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, AlertTriangle, Play, ShieldCheck, Server, Network, ArrowRight, RefreshCw} from 'lucide-react';
import './style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8080/api';
async function request(path,options={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...options.headers},...options});if(!r.ok)throw new Error((await r.json()).message||'Request failed');return r.status===204?null:r.json()}
const Badge=({value})=><span className={'badge '+String(value).toLowerCase().replace(' ','-')}>{value}</span>;
function App(){const [page,setPage]=useState('dashboard'),[clusters,setClusters]=useState([]),[data,setData]=useState({}),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const load=async()=>{try{const [c,a,p,i]=await Promise.all([request('/clusters'),request('/analytics/overview'),request('/predictions'),request('/incidents')]);setClusters(c);setData({analytics:a,predictions:p,incidents:i})}catch(e){setNotice(e.message)}};useEffect(()=>{load()},[]);const simulate=async()=>{setBusy(true);try{const r=await request('/clusters/1/simulate',{method:'POST',body:JSON.stringify({scenario:'HOT_SHARD',randomSeed:12345,durationSeconds:60})});setNotice(`Simulation complete: ${r.eventsGenerated} deterministic telemetry events generated.`);await load()}catch(e){setNotice(e.message)}finally{setBusy(false)}};const act=async(id,action)=>{try{await request(`/incidents/${id}/${action}`,{method:'POST'});setNotice(`Remediation ${action}d.`);await load()}catch(e){setNotice(e.message)}};const nav=[['dashboard','Dashboard',Activity],['topology','Topology',Network],['simulation','Simulation',Play],['predictions','Predictions',AlertTriangle],['incidents','Incidents',ShieldCheck],['analytics','Analytics',Server]];return <div className="app"><aside><div className="brand"><span className="logo">P</span><div>Predictive<span>Shard</span><small>AI RELIABILITY CONSOLE</small></div></div><nav>{nav.map(([id,label,Icon])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><Icon size={18}/>{label}</button>)}</nav><div className="cluster">CLUSTER<br/><strong>Demo Commerce</strong><Badge value="HEALTHY"/></div></aside><main><header><div><p className="eyebrow">OPERATIONS / {page.toUpperCase()}</p><h1>{page==='dashboard'?'Infrastructure overview':page[0].toUpperCase()+page.slice(1)}</h1></div><button className="outline" onClick={load}><RefreshCw size={16}/> Refresh</button></header>{notice&&<div className="notice">{notice}</div>}{page==='dashboard'&&<Dashboard data={data} clusters={clusters} go={setPage}/>} {page==='simulation'&&<Simulation busy={busy} run={simulate}/>} {page==='topology'&&<Topology/>}{page==='predictions'&&<Predictions values={data.predictions||[]}/>} {page==='incidents'&&<Incidents values={data.incidents||[]} act={act}/>} {page==='analytics'&&<Analytics values={data.analytics||{}}/>}</main></div>}
function Dashboard({data,clusters,go}){let a=data.analytics||{};return <><section className="hero"><div><p>PROACTIVE FAILURE PREVENTION</p><h2>Predict overload before it affects customers.</h2><span>Simulate correlated telemetry, forecast risk, analyze cascade paths, and safely redistribute traffic.</span><button onClick={()=>go('simulation')}><Play size={16}/> Run HOT_SHARD demo</button></div><div className="risk-orb"><b>{Math.round((data.predictions?.at(-1)?.overloadProbability||0)*100)}%</b><small>latest risk</small></div></section><section className="metrics"><Metric label="Cluster health" value={clusters[0]?.status||'HEALTHY'} hint="Demo Commerce Cluster"/><Metric label="Predictions" value={a.totalPredictions||0} hint="Fallback-safe inference"/><Metric label="Active incidents" value={a.activeIncidents||0} hint="Confidence-gated"/><Metric label="Risk reduction" value={`${Math.round((a.averageRiskReduction||0)*100)}%`} hint="After remediation"/></section><section className="grid"><div className="card wide"><h3>Latest predicted risks</h3>{data.predictions?.length?<Predictions values={data.predictions.slice(-4)}/>:<Empty text="Run the HOT_SHARD simulation to generate deterministic telemetry and a prediction."/>}</div><div className="card"><h3>Recommended workflow</h3><ol><li>Run seeded simulation</li><li>Inspect cascade analysis</li><li>Approve redistribution</li><li>Verify risk reduction</li></ol></div></section></>}
function Metric({label,value,hint}){return <div className="metric"><p>{label}</p><strong>{value}</strong><small>{hint}</small></div>}
function Simulation({busy,run}){return <div className="card simulation"><div><p className="eyebrow">DETERMINISTIC SCENARIO</p><h2>HOT_SHARD</h2><p>Concentrates traffic on product-shard-03 to demonstrate temporal overload detection and safe preventive redistribution.</p><dl><dt>Seed</dt><dd>12345</dd><dt>Duration</dt><dd>60 seconds</dd><dt>Noise</dt><dd>5%</dd></dl><button disabled={busy} onClick={run}>{busy?'Generating telemetry…':'Start simulation'} <ArrowRight size={16}/></button></div><div className="flow">Traffic ↑<ArrowRight/>Queue ↑<ArrowRight/>CPU ↑<ArrowRight/>Latency ↑<ArrowRight/>Retries ↑</div></div>}
function Topology(){return <div className="card topology"><h2>Dependency graph</h2><p>Weighted directed dependencies used independently for cascade-risk propagation.</p><div className="nodes"><span>API Gateway</span><ArrowRight/><span>Product service</span><ArrowRight/><span>Inventory</span><ArrowRight/><span>Database</span></div><div className="nodes secondary"><span>API Gateway</span><ArrowRight/><span>Search service</span><span>Cart</span><ArrowRight/><span>Inventory</span></div></div>}
function Predictions({values}){return <div className="stack">{values.length?values.map(p=><div className="prediction" key={p.id}><div><b>Shard #{p.shardId}</b><small>{p.modelVersion} · {p.fallbackUsed?'Deterministic fallback':'ML model'}</small></div><div><Badge value={p.riskLevel}/><strong>{Math.round(p.overloadProbability*100)}%</strong><small>overload probability</small></div><div><strong>{p.estimatedTimeToFailureSeconds}s</strong><small>estimated TTF</small></div></div>):<Empty text="No predictions yet."/>}</div>}
function Incidents({values,act}){return <div className="stack">{values.length?values.map(i=><div className="incident" key={i.id}><div><Badge value={i.severity}/><h3>Incident #{i.id}</h3><p>Root shard #{i.rootShardId} · Blast radius {i.blastRadius}%</p></div><div><Badge value={i.status}/>{i.status==='DETECTED'&&<button onClick={()=>act(i.id,'recommend')}>Recommend</button>}{i.remediation?.status==='RECOMMENDED'&&<button onClick={()=>act(i.id,'approve')}>Approve</button>}{i.remediation?.status==='APPROVED'&&<button onClick={()=>act(i.id,'execute')}>Execute</button>}</div></div>):<Empty text="No active incidents. Run the demo to create one."/>}</div>}
function Analytics({values}){return <section className="metrics analytics">{Object.entries(values).map(([k,v])=><Metric key={k} label={k.replace(/([A-Z])/g,' $1')} value={String(v)} hint="Current dataset"/>)}</section>};function Empty({text}){return <div className="empty">{text}</div>}createRoot(document.getElementById('root')).render(<App/>);
