package com.predictiveshard.graph;

import java.util.*;

/** Dependency traversal is intentionally independent of prediction and persistence layers. */
public final class GraphEngine {
  public record Edge(String source, String target, double weight, double propagationFactor, double latencyMs) {}
  public record CascadeResult(String rootNode, Set<String> affectedNodes, List<List<String>> paths, Map<String,Double> riskPerNode, double totalRisk, double blastRadius) {}
  private final Map<String,List<Edge>> adjacency = new HashMap<>();
  private final Set<String> vertices = new HashSet<>();
  public GraphEngine(Collection<Edge> edges) { for (var e:edges) { adjacency.computeIfAbsent(e.source(),k->new ArrayList<>()).add(e); vertices.add(e.source()); vertices.add(e.target()); } }
  public List<String> bfs(String root) { var found=new ArrayList<String>();var q=new ArrayDeque<String>();var seen=new HashSet<String>();q.add(root);seen.add(root);while(!q.isEmpty()){var v=q.remove();found.add(v);for(var e:adjacency.getOrDefault(v,List.of()))if(seen.add(e.target()))q.add(e.target());}return found; }
  public List<String> dfs(String root) { var out=new ArrayList<String>(); dfs(root,new HashSet<>(),out); return out; }
  private void dfs(String v,Set<String> seen,List<String> out){if(!seen.add(v))return;out.add(v);for(var e:adjacency.getOrDefault(v,List.of()))dfs(e.target(),seen,out);}
  public Map<String,Double> dijkstra(String root) { var dist=new HashMap<String,Double>();vertices.forEach(v->dist.put(v,Double.POSITIVE_INFINITY));dist.put(root,0d);var q=new PriorityQueue<Map.Entry<String,Double>>(Map.Entry.comparingByValue());q.add(Map.entry(root,0d));while(!q.isEmpty()){var current=q.remove();if(current.getValue()>dist.get(current.getKey()))continue;for(var e:adjacency.getOrDefault(current.getKey(),List.of())){double d=current.getValue()+e.latencyMs();if(d<dist.get(e.target())){dist.put(e.target(),d);q.add(Map.entry(e.target(),d));}}}return dist; }
  public boolean hasCycle(){var visiting=new HashSet<String>();var visited=new HashSet<String>();for(var v:vertices)if(cycle(v,visiting,visited))return true;return false;}
  private boolean cycle(String v,Set<String> visiting,Set<String> visited){if(visiting.contains(v))return true;if(!visited.add(v))return false;visiting.add(v);for(var e:adjacency.getOrDefault(v,List.of()))if(cycle(e.target(),visiting,visited))return true;visiting.remove(v);return false;}
  public List<String> topologicalOrder(){if(hasCycle())throw new IllegalStateException("Cannot topologically order a cyclic graph");var indegree=new HashMap<String,Integer>();vertices.forEach(v->indegree.put(v,0));adjacency.values().forEach(es->es.forEach(e->indegree.merge(e.target(),1,Integer::sum)));var q=new ArrayDeque<String>();indegree.forEach((v,d)->{if(d==0)q.add(v);});var out=new ArrayList<String>();while(!q.isEmpty()){var v=q.remove();out.add(v);for(var e:adjacency.getOrDefault(v,List.of()))if(indegree.merge(e.target(),-1,Integer::sum)==0)q.add(e.target());}return out;}
  public CascadeResult cascade(String root,double rootRisk,double threshold){var risks=new HashMap<String,Double>();var paths=new ArrayList<List<String>>();var bestPath=new HashMap<String,List<String>>();var q=new PriorityQueue<Map.Entry<String,Double>>(Map.Entry.<String,Double>comparingByValue().reversed());risks.put(root,rootRisk);bestPath.put(root,List.of(root));q.add(Map.entry(root,rootRisk));while(!q.isEmpty()){var current=q.remove();if(current.getValue()<risks.getOrDefault(current.getKey(),0d))continue;for(var e:adjacency.getOrDefault(current.getKey(),List.of())){double next=current.getValue()*e.weight()*e.propagationFactor();if(next<threshold)continue;if(next>risks.getOrDefault(e.target(),0d)){risks.put(e.target(),next);var p=new ArrayList<>(bestPath.get(current.getKey()));p.add(e.target());bestPath.put(e.target(),p);q.add(Map.entry(e.target(),next));}}}paths.addAll(bestPath.values());paths.sort((a,b)->Double.compare(risks.get(b.getLast()),risks.get(a.getLast())));double total=risks.values().stream().mapToDouble(Double::doubleValue).sum();return new CascadeResult(root,Set.copyOf(risks.keySet()),paths.stream().limit(5).toList(),Map.copyOf(risks),total,vertices.isEmpty()?0:100d*risks.size()/vertices.size());}
}
